config/routes.rb
Rails.application.routes.draw do
  get 'horses/index'

  resources :horses

  root 'horses#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/horse.rb
class Horse < ApplicationRecord
	validates :ranking, presence: true, numericality: { only_integer: true }
	validates :name, presence: true, length: { minimum: 2 }
	validates :breed, presence: true, length: { minimum: 1 }
	validates :age, presence: true, numericality: { only_integer: true }
	validates :country, presence: true, length: { minimum: 2 }
	validates :score, presence: true, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/horses_controller.rb
class HorsesController < ApplicationController

	def new
		@horse = Horse.new
	end

	def index
  		@horse = Horse.all
  	end

	def create
		@horse = Horse.new(horse_params)
		if @horse.save
			redirect_to @horse
		end
	end

	def show
    	@horse = Horse.find(params[:id])
  	end

	private
  		def horse_params
    	params.require(:horse).permit(:ranking, :name, :breed, :age, :rider, :country, :score)
  	end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/horses_helper.rb
module HorsesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/horses/index.html.erb
<div id="main-container" class="container-fluid">
  <h1>Top Horses </h1>

  <div id="content" class="col-xs-7">
    <table class="table table-striped">
      <tr>
        <th>Ranking</th>
        <th>Name</th>
        <th>Breed</th>
        <th>Age</th>
        <th>Rider</th>
        <th>Country</th>
        <th>Score</th>
      </tr>
     
      <% @horse.each do |horse| %>
        <tr>
          <td><%= horse.ranking %></td>
          <td><%= horse.name %></td>
          <td><%= horse.breed %></td>
          <td><%= horse.age %></td>
          <td><%= horse.rider %></td>
          <td><%= horse.country %></td>
          <td><%= horse.score %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/horses/new.html.erb
<h1> New horse </h1>

<%= form_with scope: :horse, url: horses_path, local: true do |form| %>
   <p>
    <%= form.label :ranking %>:  <%= form.text_field :ranking %>
  </p>
  
  <p>
    <%= form.label :name %>:  <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :breed %>:  <%= form.text_field :breed %>
  </p>

  <p>
    <%= form.label :age %>:  <%= form.text_field :age %>
  </p>

  <p>
    <%= form.label :rider %>:  <%= form.text_field :rider %>
  </p>

  <p>
    <%= form.label :country %>:  <%= form.text_field :country %>
  </p>

   <p>
    <%= form.label :score %>:  <%= form.text_field :score %>
  </p>
 
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/horses/show.html.erb
<p>
  <strong>Ranking:</strong>
  <%= @horse.ranking %>
</p>
 
<p>
  <strong>Name:</strong>
  <%= @horse.name %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @horse.breed %>
</p>

<p>
  <strong>Age:</strong>
  <%= @horse.age %>
</p>

<p>
  <strong>Rider:</strong>
  <%= @horse.rider %>
</p>

<p>
  <strong>Country:</strong>
  <%= @horse.country %>
</p>

<p>
  <strong>Score:</strong>
  <%= @horse.score %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HorseRankings</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>